# 自定义属性
com.bigdata.learnsb.name: caiweixiang
com.bigdata.learnsb.title: learning spring boot
com.bigdata.learnsb.environment: dev
# 参数间的引用
com.bigdata.learnsb.desc: ${com.bigdata.learnsb.name}--spring boot projects

# 随机字符串
com.bigdata.learnsb.value: ${random.value}
# 随机int
com.bigdata.learnsb.number: ${random.int}
# 随机long
com.bigdata.learnsb.bignumber: ${random.long}
# 10以内的随机数
com.bigdata.learnsb.test1: ${random.int(10)}
# 10-20的随机数
com.bigdata.learnsb.test2: ${random.int[10,20]}

# 端口设置
server:
  port: 8888
